Allow configmaps to read saml.useExistingSecret flag
anchore/anchore-charts pull request #109
Opened 2021-01-13 22:07 UTC by adawalli

There is currently a bug that requires the saml.secret value to be set
regardless of the value of saml.useExistingSecret. This changes
addresses this issue.

fixes: https://github.com/anchore/anchore-charts/issues/108

Signed-off-by: Adam Wallis <adam.wallis@gmail.com>

2021-01-15 01:13 UTC, Btodhunter approved these changes
Thanks @adawalli! Very good catch. LGTM.

2021-01-15 01:18 UTC, Btodhunter requested changes
@adawalli sorry, I may have approved this a little too quickly. Just had it dawn on me that I'd rather have the SAML secret _always_ get setup as an ENV var in secrets.yaml

To accomplish that, I think the conditional should be:
```
{{- if or .Values.anchoreGlobal.saml.secret .Values.anchoreGlobal.saml.useExistingSecret }}
secret: ${ANCHORE_SAML_SECRET}
{{- end }}
```

2021-01-15 15:46 UTC, adawalli commented
ah, that makes sense - working on it now

2021-01-15 15:54 UTC, adawalli commented
There you go @Btodhunter !

2021-01-16 02:25 UTC, Btodhunter approved these changes
LGTM! Thanks @adawalli

2021-01-16 02:26 UTC, merged