Fix duplicate secretRef
anchore/anchore-charts pull request #134
Opened 2021-04-06 18:48 UTC by kroussou

While upgrading anchore-engine chart from 1.12.1 to 1.12.7 I've noticed that an extra secretRef entry was added everywhere where existing secret was referenced.
```
        envFrom:
        - secretRef:
            name: anchore-engine-secret
        - secretRef:
            name: anchore-engine-secret
        - configMapRef:
```

This is generated by the following lines in deployment templates when `.Values.anchoreGlobal.existingSecret` is set in values file:
```
        - secretRef:
            name: {{ default (include "anchore-engine.fullname" .) .Values.anchoreGlobal.existingSecret }}
        - secretRef:
            name: {{ default (print (include "anchore-engine.fullname" .) "-admin-pass") .Values.anchoreGlobal.existingSecret }}
```

To avoid duplication and produce cleaner output I suggest replacing these lines everywhere with
```
        {{- if .Values.anchoreGlobal.existingSecret }}
        - secretRef:
            name: {{ .Values.anchoreGlobal.existingSecret }}
        {{- else }}
        - secretRef:
            name: {{ include "anchore-engine.fullname" . }}
        - secretRef:
            name: {{ print (include "anchore-engine.fullname" .) "-admin-pass" }}
        {{- end }}
```

2021-04-07 22:10 UTC, Btodhunter commented
@kroussou Thanks for the PR! This looks like a good fix to the chart, nice catch. I'll approve after doing some manual testing.

2021-04-14 06:50 UTC, Btodhunter requested changes

2021-04-14 06:50 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_ui_deployment.yaml
> +            name: {{ .Values.anchoreGlobal.existingSecret }}
This should use `.Values.anchoreEnterpriseUi.existingSecret`

2021-04-14 06:50 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_ui_deployment.yaml
> +            name: {{ include "anchore-engine.fullname" . }}
This should use `anchore-engine.enterprise-ui.fullname`

2021-04-14 06:50 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_feeds_upgrade_job.yaml
> +            name: {{ .Values.anchoreGlobal.existingSecret }}
This should use `.Values.anchoreEnterpriseFeeds.existingSecret`

2021-04-14 06:50 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_feeds_upgrade_job.yaml
> +            name: {{ include "anchore-engine.fullname" . }}
This should use `anchore-engine.enterprise-feeds.fullname`

2021-04-14 06:50 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
> +            name: {{ include "anchore-engine.fullname" . }}
This should use `anchore-engine.enterprise-feeds.fullname`

2021-04-14 06:50 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
> +            name: {{ .Values.anchoreGlobal.existingSecret }}
This should use `.Values.anchoreEnterpriseFeeds.existingSecret`

2021-04-14 17:30 UTC, Btodhunter commented
@kroussou This looks great! I just noticed a few secret references that need to be updated before we can merge.

2021-04-16 07:56 UTC, kroussou commented
@Btodhunter Mess with EE secret refs is cleaned thanks to your comments

2021-04-16 20:36 UTC, Btodhunter approved these changes
LGTM!

2021-04-16 20:37 UTC, merged