Fix handling of sslmode=require
anchore/anchore-charts pull request #145
Opened 2021-05-12 21:50 UTC by meln5674

Remove the sslrootcert parameter from the postgres connection string
  if sslmode=require. Otherwise, this has the same effect as setting
  sslmode=verify-ca.

Signed-off-by: Andrew Melnick <meln5674@kettering.edu>

See https://www.postgresql.org/docs/9.1/libpq-ssl.html

2021-05-26 21:47 UTC, robertp commented
Hey @meln5674 this looks nice, we'll do some testing on it shortly. Thank you!

2021-06-09 22:13 UTC, Btodhunter requested changes
@meln5674 Thanks for the PR! It looks good except the indentation issue I pointed out. I fixed that locally and almost everything spun up great with `sslMode=require`. 

This PR also pointed out to me that the DB config for the UI has the sslMode hard-coded. We'll need to to make some updates to support `sslMode=require`:

* `templates/enterprise_ui_deployment.yaml` - line 85 should be
```
{{ with .Values.anchoreGlobal.dbConfig.sslRootCertName }}
- name: PGSSLROOTCERT
  value: /home/anchore/certs/{{- . }}
{{- end }}
```
* `templates/enterprise_ui_secret.yaml`
```
  {{- if .Values.anchoreGlobal.dbConfig.ssl }}
  ANCHORE_APPDB_URI: 'postgresql://{{ index .Values "postgresql" "postgresUser" }}:{{ index .Values "postgresql" "postgresPassword" }}@{{ template "db-hostname" . }}/{{ index .Values "postgresql" "postgresDatabase" }}?ssl={{- .Values.anchoreGlobal.dbConfig.sslMode }}'
  {{- else }}
  ANCHORE_APPDB_URI: 'postgresql://{{ index .Values "postgresql" "postgresUser" }}:{{ index .Values "postgresql" "postgresPassword" }}@{{ template "db-hostname" . }}/{{ index .Values "postgresql" "postgresDatabase" }}'
  {{- end }}
```

2021-06-09 22:13 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_feeds_configmap.yaml
> +      db_connect_args:
@meln5674 `db_connect_args:` needs to have the same indentation as `db_connect:` - this is causing the feeds service pod to fail to start.

2021-06-09 22:28 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_feeds_upgrade_job.yaml
> +            anchore-enterprise-manager db --db-use-ssl --db-connect postgresql://${ANCHORE_DB_USER}:${ANCHORE_FEEDS_DB_PASSWORD}@${ANCHORE_DB_HOST}/${ANCHORE_DB_NAME}?sslmode={{- .Values.anchoreGloba
the white space chomping at the end of `{{- .Values.anchoreGlobal.dbConfig.sslRootCertName -}}` is causing the upgrade job to fail.

2021-06-09 22:37 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_feeds_upgrade_job.yaml
> +            anchore-enterprise-manager db --db-use-ssl --db-connect postgresql://${ANCHORE_DB_USER}:${ANCHORE_FEEDS_DB_PASSWORD}@${ANCHORE_DB_HOST}/${ANCHORE_DB_NAME}?sslmode={{- .Values.anchoreGloba
This line also has the over-zealous white space chomping on `{{- .Values.anchoreGlobal.dbConfig.sslMode -}}`

2021-06-10 20:50 UTC, Btodhunter commented
@meln5674 There are just a few more things that need to be resolved for this to work as expected. I outlined them in the comments above this one. I made all those changes locally and everything came up perfectly with `sslMode=require`. So once those are implemented I'll merge it!

2021-08-16 18:21 UTC, Btodhunter commented
@meln5674 I wanted to check in on this PR before it became too stale. It's a great addition to the chart, it just needs a few tweaks before we can merge. I plan on implementing these changes with the required tweaks in a couple of weeks if I don't hear back from you. Thanks!

2021-08-31 07:32 UTC, closed without merging