Remove inaccurate checksum when existingSecret
anchore/anchore-charts pull request #198
Opened 2022-03-18 02:01 UTC by flickerfly

When the .Values.anchoreEnterpriseUi.existingSecret is set, ignore the injection of the checksum because it will be inaccurate.

Fixes #197

2022-03-18 02:03 UTC, flickerfly commented
Just FYI, I'm not a "first-time contributor" in the whole of Anchore, just this repo: 
https://github.com/anchore/anchore-cli/pull/92

2022-03-21 19:30 UTC, flickerfly commented
Provided a version bump for the impacted chart in latest commit.

2022-03-31 17:26 UTC, Btodhunter requested changes

2022-03-31 17:26 UTC, Btodhunter commented on stable/anchore-engine/templates/enterprise_feeds_deployment.yaml
> +      {{- if not (or .Values.inject_secrets_via_env .Values.anchoreEnterpriseUi.existingSecret) }}
It looks like there is a typo in this line. The existing secret for the feeds service comes from `.Values.anchoreEnterpriseFeeds.existingSecret`

2022-03-31 17:28 UTC, Btodhunter commented
Thanks so much for the PR @flickerfly! This is a great change. I'll approve/merge as soon as the requested changes are made.

2022-04-01 23:33 UTC, Btodhunter approved these changes
lgtm!

2022-04-01 23:35 UTC, merged