adding default value for catalog imageGCMaxWorkerThreads
anchore/anchore-charts pull request #199
Opened 2022-03-30 14:05 UTC by d3vdr3y

Signed-off-by: Andre Neufville <leoneuf1@gmail.com>

2022-03-30 16:33 UTC, blang9238 submitted a review, later dismissed
lgtm!

2022-03-31 17:24 UTC, Btodhunter requested changes
I talked with Vijay about this configuration option, and it is not something we want to expose for customers to change at will. They should get guidance from CX for making this change. To accommodate that, we should remove the default value from the values file `anchoreCatalog.imageGCMaxMaxWorkerThreads`

2022-04-12 23:36 UTC, Btodhunter approved these changes

2022-04-13 01:31 UTC, Btodhunter approved these changes

2022-04-13 01:31 UTC, merged